name: '🐞 Bug Report'
description: Report a bug in our systems! oh no...
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report, you da best!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please include a detailed list of how can we reproduce this bug.
      placeholder: How did we get here anyway?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: dropdown
    id: services
    attributes:
      label: Affected services
      description: Please select the affected services
      multiple: true
      options:
        - Frontend
        - Backend
        - Infrastructure
        - Deployment
        - Shared Packages
  - type: markdown
    attributes:
      value: 'Thanks for completing our form and submitting this bug report!'
