name: Sync develop to main

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch main branch
        run: |
          git fetch origin main

      - name: Merge develop into main
        run: |
          git checkout main
          git merge origin/develop --no-edit || true

      - name: Push changes to main
        run: |
          git push origin main
